### ISSUE TITLE
hyphenated parameters

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#107]
While giving a presentation on gabbi, I noticed that the use of underscores in request/response parameters seems somewhat inconsistent:

```yaml
tests:

- name: ...
  GET: /

  response_headers:
    Content-Type: application/json
```

For HTTP headers¹ the convention is to use hyphens while gabbi parameters use underscores. For the pedantically inclined, that's an unpleasant clash.

I realize it might be too late to change this now, unless we're willing to magically accept both. Either way, it seemed worth mentioning for posterity.

¹ arguably, to a lesser extent, also for JSON keys
