### ISSUE TITLE
Unable to express header not being present in response

### ISSUE THREAD

**Issue by cdent** [cdent/gabbi#108]
When attempting to translate some python tests to gabbi I (@cdent) was unable to translate a test that was asserting that a particular header was _not_ present in the response.

It's currently impossible to make these kinds of negative assertions (not just of headers, but that's the case that came up) and it's likely we need to make it possible.

Syntax is a confusing issue:

* The current value for `response_headers` is a dict of key (header) value pairs. If we want to say "this header is not present" that doesn't fit in that structure.
* If we want to express this thing (e.g. header) is present but does _not have value X_ that is semantically different from expressing not being present. We need to think about both when designing to avoid suboptimal grammar for both.

**Comment by jasonamyers** [comment]
maybe move it to a list of dicts so we can have things like:

```yaml
- header: Content-Type,
  value: Application/XML,
  operator: not
- header: Link,
  present: False
```

Then have thing with smart defaults like operator defaulting to equals and present to True. This way we have an extensible way going forward to addition things as needed.

**Comment by cdent** [comment]
Thanks for the input @jasonamyers. The difficulties with that model are:

* it would be nice to maintain some kind of backwards compatibility as a general rule, especially in the yaml format
* this is a pretty big step away from at lease some aspects of the syntax looking _vaguely_ like raw HTTP

Of course a statement of "this header is not there" is not something that HTTP says, so we're not going to get that.

An idea that came up in IRC is a new top level key like:

```yaml
tests:
  - name: foobar
    GET: /
    response_headers:
        content-type: application/xml
    negative_response_headers:
        - x-auth-token
```

The name `negative_response_headers` is horrible.
