### ISSUE TITLE
assertion for entire response body

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#113]
It's currently not possible to reliably check whether a JSON response is an empty object:

```yaml
response_strings:
- "{}"
```

seems to be the closest we can get, but could easily result in false positives for nested objects.

Even negation (which isn't supported by JSONPath anyway, AFAIK) wouldn't help, as there might not be a fixed list of keys to blacklist.

Thus it seems like we need some sort of `response_body` assertion, comparing against the entire body? Of course that'll inevitably raise the question of leading/trailing whitespace...

**Comment by cdent** [comment]
Seems like there could be a few different ways to do this:

```yaml
response_body_string: "{}"
```

Internally this one would strip() the response and compare it with the provided string. Another option is:

```yaml
response_body_json: {}
```

that would mean the return is json, and is an empty dict. It could also:

```yaml
response_body_json:
    objects: ['alpha', 'beta', 'gamma']
```

which would mean the body is only:

```json
{"objects": ["alpha", "beta", "gamma"]}
```

I've resisted doing the latter because I think it will encourage people to validate their serializers in gabbi, which is not desirable for readable tests.

**Comment by cdent** [comment]
I haven't tested this yet but I think it may be possible to assert fully body response using response_json_paths:

```yaml
- name: assert empty string response
   GET: /
   response_json_paths:
      $: ""
```

```yaml
- name: assert empty object response
   GET: /
   response_json_paths:
      $: {}
```

```yaml
- name: assert empty list response
   GET: /
   response_json_paths:
      $: []
```

the key here being that $ is "root" or something like that. Maybe. Need to test.
