### ISSUE TITLE
evaluate if response_json_paths needs to do _replace_response_values

### ISSUE THREAD

**Issue by cdent** [cdent/gabbi#14]
It might be useful to be able to do things like this:

```yaml
- name: showAlarm
  desc: Shows information for a specified alarm.
  url: /v2/alarms/$RESPONSE['$.alarm_id']
  method: GET
  response_json_paths:
      $.severity: low
      $.alarm_id: $RESPONSE['$.alarm_id']
      $.threshold_rule.threshold: 300.0
      $.threshold_rule.comparison_operator: eq
```

Of course the only reason this came up is because this particular API makes poor use of the location header.
