### ISSUE TITLE
url concatenation with a prefix doesn't account for the prefix in the right hand side

### ISSUE THREAD

**Issue by cdent** [cdent/gabbi#165]
If, for example, a gabbi-run is done with a prefix in the url:

```
gabbi-run http://example.com/prefix
```

against a service which produces output that has links which are absolute urls:

``` json
{"links": [{"rel": "self", "href": "/prefix/somewhere"}]}
```

following that link:

``` yaml
# assume a prior request
tests:
  name: get self
  GET: $RESPONSE['$.links[?rel = "self'].href']
```

will result in a 404 because the generated url will be GET `http://example.com/prefix/prefix/somewhere`.

This can be worked around in existing tests by using the prefix in the tests, not in the host info given to gabbi.

This is not, however, a good fix because the point of the prefix is to allow testing of services that might be mounted in different "sub directories".
