### ISSUE TITLE
Support for multipart/form-data encoding

### ISSUE THREAD

**Issue by justanotherdot** [cdent/gabbi#211]
`gabbi` supports sending specific binary data as single field by using `data: <@file`, but what would be the best way to replicate `multipart/form-data` requests? Something of the form:

```yaml
tests:
  - name: multipart/form-data test
    POST: /api/form-data-endpoint
    request_headers:
      content-type: multipart/form-data
    data:
      key: val
      file: <@kittens.png
```
multipart/form-data isn't entirely possible with the custom content handler approach as it requires modifying the Content-Type to have a boundary section identifier e.g. 

```http
Content-Type: multipart/form-data;boundary=---------------------------735323031399963166993862150
```

Trying to use fixtures as a hack doesn't work either as the fixtures don't have the test context, afaik. 

**Possible solutions**

1. Having some facility to plug in arbitrary python test code would be nice, but obviously it would have to 
  play nice with the current test harness being used. 

  ```yaml
    - name: multipart/form-data test
      POST: /api/form-data-endpoint
      request_headers:
        content-type: multipart/form-data
      run: extra-tests:multipart_request
  ```

2. Passing in the context to fixtures: then one can inject test specific checks and run code (e.g. run the 
    multipart_request check if test is named `X`. 

3. Implement builtin support for `multipart/form-data` encoding in a form similar to the first example above.

I've written a small proof of concept for point one but it's overkill for this. Personally I think point three should be the preferred as it should only require some minor changes in `make_one_test` and how `request` handles urrlib3 POSTs with fields given the passed content type, I believe.
