### ISSUE TITLE
defaults handling is case sensitive

### ISSUE THREAD

**Issue by cdent** [cdent/gabbi#213]
Given:

```yaml
defaults:
  request_headers:
      Foo-Bar: value

tests:
- name: some test
   GET: /
   request_headers:
     foo-bar: value
```

`foo-bar` will not clobber `Foo-Bar`.

This may or may not be a bug. I initially thought it was (because I got caught by it) but while writing this I realized there's no good way to make it guess well. There are likely times where case does matter in a default (consider all defaults here, not jus request headers).

If we say it is case sensitive and stick with it then it is explicit and predictable.

/cc @FND
