### ISSUE TITLE
Substitution not occurring for header key

### ISSUE THREAD

**Issue by joshleeb** [cdent/gabbi#231]
Substitution doesn't seem to occur for the key of `request_headers`. For example:

Having this test works as expected, where `$ENVIRON['HEADER_VAL']` is replaced by the value of `HEADER_VAL`.

```yaml
- name: Working test
  desc: This is a working test
  GET: /api/some/endpoint
  request_headers:
    Header-Key: $ENVIRON['HEADER_VAL']
  status: 200
```

Yet, this test doesn't work as `$ENVIRON['HEADER_KEY']` isn't substituted with `HEADER_KEY`.

```yaml
- name: Failing test
  desc: This is a failing test
  GET: /api/some/endpoint
  request_headers:
    $ENVIRON['HEADER_KEY']: $ENVIRON['HEADER_VAL']
  status: 200
```

As a side note, this may have some relevance to #219.
