### ISSUE TITLE
Test for several possible statuses in reply

### ISSUE THREAD

**Issue by balta2ar** [cdent/gabbi#248]
Hello, @cdent. Is there a way to check that HTTP reply came with one of the possible HTTP codes, not just one? For example:

```
  - name: test create user
    POST: $ENVIRON['ENDPOINT']/user/create/
    data:
        data:
            username: "testuser1"
        verbose: true
    status: any([200, 400])
```
Because either 200 or 400 is fine.
Thanks.
