### ISSUE TITLE
After moving to `httpx` an integer value in a HTTP request header returns an error

### ISSUE THREAD

**Issue by scottwallacesh** [cdent/gabbi#336]
Example test:
```yaml
tests:
  - name: request with integer header value
    url: /foo
    request_headers:
      integer: 13
```

Output:
```text
ERROR: gabbi-runner.test_integer_req_header_request_with_integer_header_value
        Header value must be str or bytes, not <class 'int'>
```
