### ISSUE TITLE
YAML defaults cannot be overridden by test specifics

### ISSUE THREAD

**Issue by kiminoa** [cdent/gabbi#39]
Feature request? It would be lovely if a test-specific could override the defaults' value.

Example:
```yaml
defaults:
    request_headers:
        accept: application/json
        content-type: application/json
    response_headers:
        content-type: application/json; charset=utf-8

<-- snip -->

tests:
    - name: delete note test case
      verbose: True
      method: DELETE
      url: /v2/notes/$RESPONSE['$.id']
      request_headers:
          accept: text/javascript
          content-type: text/javascript; charset=utf-8
      response_headers:
          content-type: text/javascript; charset=utf-8
      status: 302 || 200
```

This causes "delete note test case" to return application/json. 

Workaround: If I nix the defaults and specify content-type and accept header details for each test, all is well.
