### ISSUE TITLE
missing response header raises error rather than failure

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#60]
The following reports an error when it should report a failure instead:

```yaml
tests:

  - name: failure
    url: http://google.com

    status: 302
    response_headers:
        x-foo: bar
```

AFAICT that's because internally a `KeyError` is raised ("'x-foo' header not available in response keys: dict_keys(...)"): `testtools.TestCase`'s default `exception_handlers` doesn't have a mapping for that particular exception, so it defaults to `_report_error` rather than using `_report_failure`.
