### ISSUE TITLE
Ability to use any response in a scenario

### ISSUE THREAD

**Issue by jd** [cdent/gabbi#78]
My need here is not only use the previous response via `$REPONSE`, but anyone in the scenario. In Gnocchi we need to create 2 metrics with 2 different request, that will each return an ID, and then use both those id in a subsequent request. That could be achieved by having `$REPONSES` being a dict and an array like object that can be accessed via the test name of the test number (relative or absolute), e.h.:

```
tests:
    - name: create archive policy
      desc: for later use
      url: /v1/archive_policy
      method: POST
      request_headers:
        content-type: application/json
        x-roles: admin
      data:
        name: high
        definition:
          - granularity: 1 second
      status: 201

    - name: create metric
      url: /v1/metric
      request_headers:
        content-type: application/json
      method: post
      data:
        archive_policy_name: "high"
      status: 201

    - name: create metric 2
      url: /v1/metric
      request_headers:
        content-type: application/json
      method: post
      data:
        archive_policy_name: "high"
      status: 201

    - name: search measure
      url: /v1/search/metric?metric_id=$RESPONSES[-1]['$.id']&metric_id=$REPONSES[-2]['$.id']
      method: post
      request_headers:
        content-type: application/json
      data:
        ∧:
          - ≥: 1000
      status: 400
      response_strings:
        - Invalid value for start
```

**Comment by cdent** [comment]
In this particular case you could inject a test after `create metric 2` and then modify the search measure test as follows:

```yaml

  - name: get metric list
    url: /v1/metric
    request_headers:
        content-type: application/json

  - name: search measure
    url: /v1/search/metric?metric_id=$RESPONSE['$[0].id']&metric_id=$RESPONSE['$[1].id']

    [...]
```

Part of the reason that gabbi doesn't allow multi-stage investigation of responses is to help insure that test represent a flow where the client side isn't really maintaining any state other than the state is comes in with. Gabbi has the opinion that an API should provide collection resources that make it possible for "recently created resouces" to be retrieved. It also assumes that there will be sufficient test isolation such that a query like the GET on /v1/metric that I've added above will return a sufficiently small set of results to be useful to feed further requests.

I'm not 100% "no" on this idea, but at least with this use case I think it would detract from the linear readability of the test and make it necessary to hop around and count backwards in the file too much.

Rebuttal?

**Comment by FND** [comment]
I'm not keen on this either. If it is deemed necessary, we should at least requirex explicit markers on tests that are referenced later, e.g.

```yaml
persist: true # later referenced as `$RESPONSE[<test name>]`
---
persist: <key> # later referenced as `$RESPONSE[<key>]`
```
