### ISSUE TITLE
support for form data

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#96]
Testing HTML forms currently requires manually encoding the submitted data:

``` yaml
- name: create new item
  POST: /items
  request_headers:
      Content-Type: application/x-www-form-urlencoded
  data: name=foo
```

This gets unwieldy as soon as there are multiple parameters and/or the data requires encoding:

``` yaml
  data: name=hello%20world&desc=l%C3%B6r%C3%A4m%20ips%C3%BCm&tag=foo&tag=bar&...
```

(that's still a fairly tame example)

This greatly impedes readability. It also seems inconsistent, given the support for structured data in `query_parameters` and JSON request bodies (the docs specifically mention that this allows "more flexibility when doing a `POST` or `PUT`" - there's no reason this affordance should be limited to JSON).

Since form submissions - or, more generally, `application/x-www-form-urlencoded` - is fairly common, even beyond browser-based applications (i.e. also used in APIs), gabbi should auto-encode form data (as determined by the `Content-Type` header):

``` yaml
  data:
      name: hello world
      desc: löräm ipsüm
      tag: 
      - foo
      - bar
```

(Arguably we might also want to support an ordered sequence of key-value pairs.)
